# Generated by Django 5.0.2 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('student_name', models.CharField(max_length=20)),
                ('id_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('BookName', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('author_name', models.CharField(max_length=20)),
                ('Total_page', models.IntegerField()),
            ],
        ),
    ]
